	git add  config.txt
	git add  static/images/board.png
	git add  static/images/car_move.gif
	git add  static/images/car_move_blocked.gif
	git add  static/images/car_move_h.gif
	git add  static/images/car_move_v.gif
	git add  static/images/images_to_gif/1.png
	git add  static/images/images_to_gif/2.png
	git add  static/images/images_to_gif/3.png
	git add  static/images/images_to_gif/4.png
	git add  static/js/task.js
	git add  static/json/empty.json
	git add  static/json/empty_h.json
	git add  static/json/empty_plus.json
	git add  static/json/empty_v.json
	git add  templates/ad.html
	git add  templates/consent.html
	git add  templates/instructions/instruct-1.html
	git add  templates/instructions/instruct-2.html
	git add  templates/instructions/instruct-2_2.html
	git add  templates/instructions/instruct-3.html
	git add  templates/instructions/instruct-5.html
	git add  templates/instructions/instruct-6.html
	git add  ../results/summary_stats.R
	git add  ../src/instance_generator.py
	git add static/images/blocked.gif
	git add static/images/blocked.vgc
	git add static/images/images_to_gif/blocked1.png
	git add static/images/images_to_gif/blocked2.png
	git add static/images/images_to_gif/board.png
	git add static/images/images_to_gif/h1.png
	git add static/images/images_to_gif/h2.png
	git add static/images/images_to_gif/h3.png
	git add static/images/images_to_gif/red1.png
	git add static/images/images_to_gif/red2.png
	git add static/images/images_to_gif/red3.png
	git add static/images/images_to_gif/red4.png
	git add static/images/images_to_gif/v1.png
	git add static/images/images_to_gif/v2.png
	git add static/images/images_to_gif/v3.png
	git add static/images/move_h.gif
	git add static/images/move_h.vgc
	git add static/images/move_red.gif
	git add static/images/move_red.vgc
	git add static/images/move_v.gif
	git add static/images/move_v.vgc
